STRINGS = {
    "app_title": "🔐 Passwort-Manager",
    
    "menu_database": "Datenbank",
    "menu_edit": "Bearbeiten", 
    "menu_tools": "Extras",
    "menu_view": "Ansicht",
    "menu_help": "Hilfe",
    
    "menu_db_new": "Neue Datenbank...",
    "menu_db_open": "Datenbank öffnen...",
    "menu_db_save": "Datenbank speichern",
    "menu_db_save_as": "Datenbank speichern unter...",
    "menu_db_import": "Importieren...",
    "menu_db_export": "Exportieren...",
    "menu_db_settings": "Datenbank-Einstellungen...",
    "menu_db_change_key": "Master-Passwort ändern...",
    "menu_db_lock": "Datenbank sperren",
    "menu_db_exit": "Beenden",
    
    "menu_edit_add": "Eintrag hinzufügen",
    "menu_edit_edit": "Eintrag bearbeiten", 
    "menu_edit_clone": "Eintrag duplizieren",
    "menu_edit_delete": "Eintrag löschen",
    "menu_edit_copy_user": "Benutzername kopieren",
    "menu_edit_copy_pass": "Passwort kopieren",
    "menu_edit_copy_url": "URL kopieren",
    "menu_edit_copy_totp": "2FA-Code kopieren",
    "menu_edit_select_all": "Alle auswählen",
    "menu_edit_find": "Suchen...",
    
    "menu_tools_generator": "Passwort-Generator",
    "menu_tools_totp": "2FA-Manager",
    "menu_tools_backup": "Datenbank-Backup",
    "menu_tools_import_backup": "Backup importieren",
    "menu_tools_check_passwords": "Passwort-Stärke prüfen",
    "menu_tools_find_duplicates": "Doppelte Passwörter finden",
    "menu_tools_settings": "Einstellungen...",
    
    "menu_view_refresh": "Aktualisieren",
    "menu_view_sort_by": "Sortieren nach",
    "menu_view_sort_title": "Nach Titel sortieren",
    "menu_view_sort_username": "Nach Benutzername sortieren", 
    "menu_view_sort_url": "Nach URL sortieren",
    "menu_view_sort_modified": "Nach Änderungsdatum sortieren",
    "menu_view_show_toolbar": "Symbolleiste anzeigen",
    "menu_view_show_status": "Statusleiste anzeigen",
    "menu_view_entry_details": "Eintrag-Details",
    
    "menu_help_shortcuts": "Tastenkürzel",
    "menu_help_getting_started": "Erste Schritte",
    "menu_help_check_updates": "Nach Updates suchen",
    "menu_help_report_issue": "Problem melden",
    "menu_help_about": "Über Passwort-Manager",
    
    "toolbar_new": "Neu",
    "toolbar_edit": "Bearbeiten", 
    "toolbar_delete": "Löschen",
    "toolbar_copy": "Kopieren",
    "toolbar_user": "Benutzer",
    "toolbar_generate": "Generieren",
    "toolbar_2fa": "2FA",
    "toolbar_backup": "Backup",
    "toolbar_settings": "Einstellungen",
    "toolbar_search": "Suchen:",
    
    "table_title": "Titel",
    "table_username": "Benutzername",
    "table_password": "Passwort", 
    "table_url": "URL",
    "table_2fa": "2FA",
    "table_modified": "Geändert",
    "table_header": "Passwort-Einträge",
    
    "button_ok": "OK",
    "button_cancel": "Abbrechen",
    "button_close": "Schließen",
    "button_save": "Speichern",
    "button_back": "Zurück",
    "button_login": "Anmelden",
    "button_open": "Öffnen",
    "button_new_database": "Neue Datenbank",
    "button_import_backup": "Backup importieren",
    "button_refresh": "Aktualisieren",
    "button_delete": "Löschen",
    "button_generate": "Generieren",
    "button_use": "Verwenden",
    "button_search": "Suchen",
    
    "dialog_add_password": "Neues Passwort hinzufügen",
    "dialog_edit_password": "Passwort bearbeiten",
    "dialog_password_generator": "🎲 Passwort-Generator",
    "dialog_settings": "Einstellungen",
    "dialog_backup": "Backup & Export",
    "dialog_totp_manager": "🔐 2FA/TOTP-Manager",
    "dialog_database_manager": "🗄️ Datenbank-Manager",
    "dialog_entry_details": "Eintrag-Details",
    "dialog_advanced_search": "🔍 Erweiterte Suche",
    
    "field_title": "Titel:",
    "field_username": "Benutzername:",
    "field_password": "Passwort:",
    "field_url": "URL:",
    "field_notes": "Notizen:",
    "field_master_password": "Master-Passwort:",
    "field_created": "Erstellt:",
    "field_modified": "Geändert:",
    
    "status_ready": "Bereit",
    "status_entries": "Einträge",
    "status_showing": "Zeige",
    "status_found": "Gefunden",
    "status_of": "von",
    "status_no_matches": "Keine Treffer für",
    "status_all_match": "Alle",
    "status_entries_match": "Einträge passen zu",
    "status_password_copied": "Passwort kopiert",
    "status_username_copied": "Benutzername kopiert", 
    "status_url_copied": "URL kopiert",
    "status_totp_copied": "2FA-Code kopiert",
    "status_clipboard_cleared": "Zwischenablage geleert",
    "status_entry_added": "Eintrag hinzugefügt",
    "status_entry_updated": "Eintrag aktualisiert",
    "status_entry_deleted": "Eintrag gelöscht",
    "status_database_saved": "Datenbank gespeichert",
    "status_search_cleared": "Suche gelöscht",
    "status_auto_backup": "Auto-Backup erstellt",
    "status_will_clear_in": "wird gelöscht in",
    "status_seconds": "s",
    "status_remaining": "s verbleibend",
    
    "error_title": "Fehler",
    "error_warning": "Warnung", 
    "error_info": "Information",
    "error_success": "Erfolg",
    "error_no_entry_selected": "Bitte einen Eintrag auswählen!",
    "error_title_required": "Titel ist erforderlich!",
    "error_password_required": "Passwort ist erforderlich!",
    "error_master_password_required": "Bitte Master-Passwort eingeben!",
    "error_wrong_master_password": "Falsches Master-Passwort oder keine Datenbank gefunden!",
    "error_title_exists": "Eintrag mit diesem Titel existiert bereits!",
    "error_invalid_database_name": "Ungültiger Datenbankname!",
    "error_master_password_min_length": "Master-Passwort muss mindestens 8 Zeichen haben!",
    "error_passwords_dont_match": "Passwörter stimmen nicht überein!",
    "error_database_not_found": "Datenbank nicht gefunden!",
    "error_backup_not_found": "Backup-Datei nicht gefunden!",
    "error_could_not_open_website": "Website konnte nicht geöffnet werden:",
    "error_could_not_generate_totp": "2FA-Code konnte nicht generiert werden!",
    "error_no_username_available": "Kein Benutzername verfügbar",
    "error_no_2fa_available": "Kein 2FA-Code verfügbar!",
    "error_backup_damaged": "Das Backup scheint beschädigt zu sein (Datei zu klein).",
    
    "confirm_delete_entry": "Wirklich löschen",
    "confirm_cannot_be_undone": "Dies kann nicht rückgängig gemacht werden!",
    "confirm_logout": "Wirklich abmelden?",
    "confirm_switch_database": "Datenbank wechseln? Aktuelle Sitzung wird beendet.",
    "confirm_exit_application": "Anwendung wirklich beenden?",
    "confirm_overwrite_database": "Datenbank existiert bereits.\nTrotzdem überschreiben?",
    "confirm_delete_database": "Datenbank wirklich löschen",
    "confirm_import_backup": "Daten importieren aus",
    "confirm_check_preview": "Prüfen Sie die Vorschau auf Richtigkeit.",
    "confirm_restore_backup": "Aktuelle Datenbank überschreiben mit",
    
    "placeholder_search_entries": "Einträge durchsuchen...",
    "placeholder_database_name": "Meine_Passwoerter",
    
    "tooltip_add_entry": "Neuen Passwort-Eintrag hinzufügen (Strg+N)",
    "tooltip_edit_entry": "Ausgewählten Eintrag bearbeiten (Strg+E)", 
    "tooltip_delete_entry": "Ausgewählten Eintrag löschen (Entf)",
    "tooltip_copy_password": "Passwort kopieren (Strg+C)",
    "tooltip_copy_username": "Benutzername kopieren",
    "tooltip_password_generator": "Passwort-Generator",
    "tooltip_2fa_manager": "2FA/TOTP-Manager",
    "tooltip_backup_export": "Backup & Export",
    "tooltip_settings": "Einstellungen",
    "tooltip_database_switch": "Datenbank wechseln (🔄)",
    "tooltip_logout": "Abmelden (🚪)",
    
    "info_enter_master_password": "Gib das Master-Passwort für diese Datenbank ein",
    "info_select_database": "Wähle eine Passwort-Datenbank aus oder erstelle eine neue",
    "info_double_click_open": "Doppelklick auf eine Datenbank zum direkten Öffnen",
    "info_tip_shortcuts": "Tipp: F1/F5 funktionieren überall, andere nur im Hauptfenster",
    "info_tip_double_click": "Tipp: Doppelklick auf eine Datenbank zum direkten Öffnen",
    "info_tip_context_menu": "Tipp: Rechtsklick auf Einträge für weitere Optionen",
    "info_getting_started": "Willkommen beim Passwort-Manager!\n\n• Strg+N für neue Passwörter\n• Strg+F zum Suchen\n• Rechtsklick für weitere Optionen\n• F1 für alle Tastenkürzel\n\nDeine Passwörter sind verschlüsselt und sicher!",
    "info_auto_lock": "Die Datenbank wurde automatisch gesperrt.",
    "info_latest_version": "Du verwendest die neueste Version des Passwort-Managers!",
    "info_report_issue": "Problem melden:\n\n1. Beschreibe das Problem detailliert\n2. Schritte zur Reproduktion angeben\n3. Betriebssystem erwähnen\n\nKontakt: support@passwordmanager.com",
    "info_about": "🔐 Passwort-Manager v2.0\n\nEine sichere Passwort-Verwaltung\nmit modernem Design und erweiterten Funktionen.\n\nFeatures:\n• AES-256 Verschlüsselung\n• 2FA/TOTP Unterstützung\n• Passwort-Generierung\n• Sichere Backups & Export\n• Auto-Lock Schutz\n\nErstellt mit Python & Tkinter",
    
    "settings_title": "Einstellungen",
    "settings_saved": "Einstellungen gespeichert!",
    "settings_restart_required": "Einige Änderungen erfordern einen Neustart der Anwendung.\n\nBitte melden Sie sich ab und wieder an, um alle Änderungen zu sehen.",
    "settings_automatically_saved": "Einstellungen werden automatisch gespeichert",
    "settings_tab_security": "🔒 Sicherheit",
    "settings_tab_interface": "🎨 Oberfläche", 
    "settings_tab_advanced": "⚙️ Erweitert",
    "settings_auto_lock": "🔒 Automatische Sperre",
    "settings_auto_lock_enable": "Auto-Lock aktivieren",
    "settings_timeout_minutes": "Timeout (Minuten):",
    "settings_warning_seconds": "Warnung (Sekunden):",
    "settings_clipboard": "📋 Zwischenablage",
    "settings_clipboard_enable": "Automatisches Löschen aktivieren",
    "settings_clear_after_seconds": "Löschen nach (Sekunden):",
    "settings_design": "🎨 Design",
    "settings_theme": "Theme:",
    "settings_theme_windows_classic": "Windows Klassisch",
    "settings_theme_modern": "Modern (Zukünftig)",
    "settings_theme_dark": "Dark Mode (Zukünftig)",
    "settings_window": "🖥️ Fenster",
    "settings_show_status_bar": "Statusleiste anzeigen",
    "settings_show_toolbar_icons": "Symbolleisten-Icons anzeigen",
    "settings_remember_window_size": "Fenstergröße merken",
    "settings_startup": "🚀 Programmstart",
    "settings_remember_database": "Letzte Datenbank merken",
    "settings_start_minimized": "Minimiert starten",
    "settings_import_export": "💾 Einstellungen",
    "settings_export": "📤 Exportieren",
    "settings_import": "📥 Importieren", 
    "settings_reset": "🔄 Zurücksetzen",
    "settings_language": "🌍 Sprache",
    "settings_select_language": "Sprache auswählen:",
    
    "backup_title": "Backup & Export",
    "backup_tab_backup": "💾 Backup",
    "backup_tab_export": "📤 Export",
    "backup_tab_import": "📥 Import",
    "backup_quick_actions": "⚡ Schnell-Aktionen",
    "backup_create": "🔄 Backup erstellen",
    "backup_full": "📦 Vollständiges Backup",
    "backup_available": "📋 Verfügbare Backups",
    "backup_restore": "↩️ Wiederherstellen",
    "backup_delete": "🗑️ Löschen",
    "backup_export_settings": "⚙️ Export-Einstellungen",
    "backup_include_passwords": "🔑 Passwörter im Export einschließen",
    "backup_warning": "⚠️ Achtung: Exportierte Dateien sind NICHT verschlüsselt!",
    "backup_export_formats": "📁 Export-Formate",
    "backup_export_csv": "📊 CSV exportieren",
    "backup_export_json": "📋 JSON exportieren",
    "backup_format_info": "ℹ️ Format-Informationen",
    "backup_import_settings": "⚙️ Import-Einstellungen",
    "backup_overwrite_existing": "🔄 Bestehende Einträge überschreiben",
    "backup_import_sources": "📁 Import-Quellen",
    "backup_import_csv": "📊 CSV importieren",
    "backup_restore_backup": "💾 Backup wiederherstellen",
    "backup_import_preview": "👁️ Import-Vorschau",
    "backup_statistics": "Backups",
    
    "generator_title": "🎲 Passwort-Generator",
    "generator_settings": "⚙️ Einstellungen",
    "generator_length": "Länge:",
    "generator_uppercase": "✓ Großbuchstaben (A-Z)",
    "generator_lowercase": "✓ Kleinbuchstaben (a-z)",
    "generator_numbers": "✓ Zahlen (0-9)",
    "generator_symbols": "✓ Symbole (!@#$%...)",
    "generator_exclude_ambiguous": "✓ Mehrdeutige Zeichen ausschließen (0,O,l,1...)",
    "generator_generated_password": "🔑 Generiertes Passwort",
    "generator_strength": "Stärke:",
    "generator_actions": "🎯 Aktionen",
    "generator_generate_new": "🎲 Neues Passwort",
    "generator_use_password": "✅ Verwenden",
    "generator_history": "📜 Letzte Passwörter",
    "generator_tip": "Tipp: Doppelklick auf ein Passwort aus der Historie zum Auswählen",
    
    "totp_title": "🔐 2FA/TOTP-Manager",
    "totp_subtitle": "Verwalte alle deine 2FA-Codes an einem Ort",
    "totp_active_codes": "🔑 Aktive 2FA-Codes",
    "totp_account": "📝 Account",
    "totp_current_code": "🔐 Aktueller Code",
    "totp_time": "⏱️ Zeit",
    "totp_copy_code": "📋 Code kopieren",
    "totp_show_qr": "📱 QR-Code anzeigen",
    "totp_backup_codes": "💾 Backup-Codes",
    "totp_refresh": "🔄 Aktualisieren",
    "totp_tip": "💡 Tipp: Klick auf einen Eintrag um ihn auszuwählen, dann 'Code kopieren'. Codes aktualisieren sich automatisch alle 30 Sekunden.",
    "totp_no_codes": "Keine 2FA-Codes vorhanden",
    "totp_add_2fa": "Füge 2FA zu deinen Passwörtern hinzu",
    "totp_qr_title": "📱 QR-Code für",
    "totp_secret_backup": "Secret Key (Backup):",
    "totp_copy_secret": "📋 Secret kopieren",
    "totp_backup_title": "💾 Backup Recovery Codes",
    "totp_backup_warning": "⚠️ Diese Codes können verwendet werden, wenn du keinen Zugang\nzu deiner 2FA-App hast. Bewahre sie sicher auf!",
    "totp_copy_all": "📋 Alle kopieren",
    "totp_save": "💾 Speichern",
    "totp_backup_header": "BACKUP RECOVERY CODES",
    "totp_generated": "Generiert:",
    "totp_keep_safe": "Bewahre diese Codes sicher auf!",
    "totp_codes_copied": "Alle Backup-Codes in die Zwischenablage kopiert!",
    "totp_codes_saved": "Backup-Codes gespeichert:",
    "totp_could_not_save": "Konnte Datei nicht speichern:",
    "totp_code_copied": "2FA-Code kopiert!",
    "totp_valid_for": "Gültig für weitere",
    "totp_secret_copied": "Secret Key in die Zwischenablage kopiert!",
    
    "password_strength_very_weak": "Sehr schwach",
    "password_strength_weak": "Schwach",
    "password_strength_medium": "Mittel",
    "password_strength_strong": "Stark", 
    "password_strength_very_strong": "Sehr stark",
    
    "database_manager_title": "🗄️ Datenbank-Manager",
    "database_manager_subtitle": "Wähle eine Passwort-Datenbank aus oder erstelle eine neue",
    "database_available": "📂 Verfügbare Datenbanken",
    "database_name": "📝 Datenbankname",
    "database_size": "📏 Größe",
    "database_modified": "🕐 Zuletzt geändert",
    "database_none_found": "Keine Datenbanken gefunden",
    "database_create_new": "Erstelle eine neue Datenbank!",
    "database_found": "Datenbank",
    "database_found_plural": "Datenbanken gefunden",
    
    "context_edit_entry": "✏️ Eintrag bearbeiten",
    "context_copy_password": "📋 Passwort kopieren",
    "context_copy_username": "👤 Benutzername kopieren",
    "context_copy_2fa": "🔐 2FA-Code kopieren",
    "context_copy_url": "🔗 URL kopieren",
    "context_open_website": "🌐 Öffnen",
    "context_no_url": "🌐 Website öffnen (keine URL)",
    "context_search_similar": "🔍 Ähnliche suchen",
    "context_duplicate_entry": "📝 Eintrag duplizieren",
    "context_delete_entry": "🗑️ Eintrag löschen",
    "context_entry_details": "ℹ️ Eintrag-Details",
    "context_password_strength": "📊 Passwort-Stärke",
    
    "details_title": "ℹ️",
    "details_for": "Details für",
    "details_info": "Eintrag-Informationen",
    "details_title_field": "📝 Titel:",
    "details_username_field": "👤 Benutzername:", 
    "details_password_field": "🔑 Passwort:",
    "details_url_field": "🌐 URL:",
    "details_2fa_field": "🔐 2FA:",
    "details_created_field": "📅 Erstellt:",
    "details_modified_field": "✏️ Geändert:",
    "details_notes_field": "📋 Notizen",
    "details_not_specified": "(nicht angegeben)",
    "details_empty": "(leer)",
    "details_enabled": "Aktiviert",
    "details_disabled": "Deaktiviert",
    "details_unknown": "Unbekannt",
    "details_copy_password": "📋 Passwort",
    "details_copy_user": "👤 Benutzer",
    "details_open_url": "🌐 Öffnen",
    
    "strength_dialog_title": "Passwort-Stärke",
    "strength_dialog_for": "Passwort-Stärke für",
    "strength_dialog_strength": "Stärke:",
    "strength_dialog_score": "Bewertung:",
    "strength_dialog_length": "Länge:",
    "strength_dialog_characters": "Zeichen",
    
    "weak_passwords_title": "Schwache Passwörter",
    "weak_passwords_found": "Schwache Passwörter gefunden:",
    "weak_passwords_and_more": "... und",
    "weak_passwords_more": "weitere",
    "weak_passwords_none": "Alle Passwörter sind stark!",
    
    "duplicate_passwords_title": "Doppelte Passwörter", 
    "duplicate_passwords_found": "Doppelte Passwörter gefunden:",
    "duplicate_passwords_used_by": "Passwort verwendet von:",
    "duplicate_passwords_groups": "weitere Gruppen",
    "duplicate_passwords_none": "Keine doppelten Passwörter gefunden!",
    
    "duplicate_entry_title": "Eintrag duplizieren",
    "duplicate_entry_copy": "(Kopie)",
    "duplicate_entry_success": "Eintrag dupliziert:",
    "duplicate_entry_error": "Konnte Eintrag nicht duplizieren. Titel bereits vorhanden?",
    
    "auto_lock_warning_title": "⚠️ Auto-Lock Warnung",
    "auto_lock_warning_title_short": "Automatische Sperre",
    "auto_lock_warning_text": "Die Datenbank wird aus Sicherheitsgründen automatisch gesperrt,\nda keine Aktivität erkannt wurde.\n\n💡 Tipp: In geöffneten Dialogen wird der Timer automatisch pausiert.",
    "auto_lock_warning_locking_in": "Sperre in",
    "auto_lock_warning_seconds": "Sekunden",
    "auto_lock_warning_continue": "✅ Weiter arbeiten",
    "auto_lock_warning_lock_now": "🔒 Jetzt sperren",
    
    "search_advanced_title": "🔍 Erweiterte Suche",
    "search_term": "Suchbegriff:",
    "search_results": "Suchergebnisse:",
    "search_in": "Suchen in:",
    "search_in_title": "Titel",
    "search_in_username": "Benutzername",
    "search_in_url": "URL", 
    "search_in_notes": "Notizen",
    
    "csv_preview": "📊 CSV-Vorschau:",
    "csv_fields": "Felder:",
    "csv_row": "Zeile",
    "csv_no_data": "❌ Keine gültigen Daten gefunden",
    "csv_more_rows": "... (weitere Zeilen verfügbar)",
    "csv_error_reading": "❌ Fehler beim Lesen der CSV-Datei:",
    
    "import_csv_title": "CSV-Import",
    "import_csv_from": "Daten importieren aus",
    "import_csv_success": "CSV-Import:",
    "import_csv_imported": "Einträge importiert",
    "import_csv_conflicts": "Konflikte",
    "import_csv_error": "CSV-Import-Fehler:",
    
    "export_csv_title": "CSV-Export speichern",
    "export_json_title": "JSON-Export speichern", 
    "export_csv_success": "CSV-Export erstellt:",
    "export_json_success": "JSON-Export erstellt:",
    "export_csv_error": "CSV-Export-Fehler:",
    "export_json_error": "JSON-Export-Fehler:",
    
    "backup_create_title": "Vollständiges Backup speichern",
    "backup_created": "Vollständiges Backup erstellt:",
    "backup_restored": "Backup wiederhergestellt:",
    "backup_deleted": "Backup gelöscht",
    "backup_error": "Backup-Fehler:",
    "backup_restore_error": "Wiederherstellungs-Fehler:",
    "backup_delete_error": "Lösch-Fehler:",
    "backup_import_title": "Backup-Datei auswählen",
    "backup_import_name": "Name für die importierte Datenbank:",
    "backup_import_success": "Backup erfolgreich importiert als",
    "backup_import_error": "Backup konnte nicht importiert werden:",
    "backup_import_open_now": "Möchten Sie die importierte Datenbank jetzt öffnen?",
    
    "login_title": "🔐",
    "login_database": "Datenbank:",
    "login_back": "⬅️ Zurück",
    "login_login": "🔓 Anmelden",
    
    "new_database_title": "Neue Datenbank",
    "new_database_name": "Name für die neue Datenbank:",
    "new_database_master_password": "Master-Passwort für",
    "new_database_confirm": "Master-Passwort wiederholen:",
    "new_database_created": "Datenbank erfolgreich erstellt!",
    "new_database_error": "Datenbank konnte nicht erstellt werden:",
    
    "file_types_backup": "Backup-Dateien",
    "file_types_encrypted": "Verschlüsselte Dateien", 
    "file_types_csv": "CSV-Dateien",
    "file_types_json": "JSON-Dateien",
    "file_types_text": "Text-Dateien",
    "file_types_zip": "ZIP-Archive",
    "file_types_all": "Alle Dateien"
}