STRINGS = {
    "app_title": "🔐 Password Manager",
    
    "menu_database": "Database",
    "menu_edit": "Edit", 
    "menu_tools": "Tools",
    "menu_view": "View",
    "menu_help": "Help",
    
    "menu_db_new": "New Database...",
    "menu_db_open": "Open Database...",
    "menu_db_save": "Save Database",
    "menu_db_save_as": "Save Database As...",
    "menu_db_import": "Import...",
    "menu_db_export": "Export...",
    "menu_db_settings": "Database Settings...",
    "menu_db_change_key": "Change Master Key...",
    "menu_db_lock": "Lock Database",
    "menu_db_exit": "Exit",
    
    "menu_edit_add": "Add Entry",
    "menu_edit_edit": "Edit Entry", 
    "menu_edit_clone": "Clone Entry",
    "menu_edit_delete": "Delete Entry",
    "menu_edit_copy_user": "Copy Username",
    "menu_edit_copy_pass": "Copy Password",
    "menu_edit_copy_url": "Copy URL",
    "menu_edit_copy_totp": "Copy 2FA Code",
    "menu_edit_select_all": "Select All",
    "menu_edit_find": "Find...",
    
    "menu_tools_generator": "Password Generator",
    "menu_tools_totp": "2FA Manager",
    "menu_tools_backup": "Database Backup",
    "menu_tools_import_backup": "Import Backup",
    "menu_tools_check_passwords": "Check Password Strength",
    "menu_tools_find_duplicates": "Find Duplicate Passwords",
    "menu_tools_settings": "Settings...",
    
    "menu_view_refresh": "Refresh",
    "menu_view_sort_by": "Sort by",
    "menu_view_sort_title": "Sort by Title",
    "menu_view_sort_username": "Sort by Username", 
    "menu_view_sort_url": "Sort by URL",
    "menu_view_sort_modified": "Sort by Modified",
    "menu_view_show_toolbar": "Show Toolbar",
    "menu_view_show_status": "Show Status Bar",
    "menu_view_entry_details": "Entry Details",
    
    "menu_help_shortcuts": "Keyboard Shortcuts",
    "menu_help_getting_started": "Getting Started",
    "menu_help_check_updates": "Check for Updates",
    "menu_help_report_issue": "Report Issue",
    "menu_help_about": "About Password Manager",
    
    "toolbar_new": "New",
    "toolbar_edit": "Edit", 
    "toolbar_delete": "Delete",
    "toolbar_copy": "Copy",
    "toolbar_user": "User",
    "toolbar_generate": "Generate",
    "toolbar_2fa": "2FA",
    "toolbar_backup": "Backup",
    "toolbar_settings": "Settings",
    "toolbar_search": "Search:",
    
    "table_title": "Title",
    "table_username": "Username",
    "table_password": "Password", 
    "table_url": "URL",
    "table_2fa": "2FA",
    "table_modified": "Modified",
    "table_header": "Password Entries",
    
    "button_ok": "OK",
    "button_cancel": "Cancel",
    "button_close": "Close",
    "button_save": "Save",
    "button_back": "Back",
    "button_login": "Login",
    "button_open": "Open",
    "button_new_database": "New Database",
    "button_import_backup": "Import Backup",
    "button_refresh": "Refresh",
    "button_delete": "Delete",
    "button_generate": "Generate",
    "button_use": "Use",
    "button_search": "Search",
    
    "dialog_add_password": "Add New Password",
    "dialog_edit_password": "Edit Password",
    "dialog_password_generator": "🎲 Password Generator",
    "dialog_settings": "Settings",
    "dialog_backup": "Backup & Export",
    "dialog_totp_manager": "🔐 2FA/TOTP Manager",
    "dialog_database_manager": "🗄️ Database Manager",
    "dialog_entry_details": "Entry Details",
    "dialog_advanced_search": "🔍 Advanced Search",
    
    "field_title": "Title:",
    "field_username": "Username:",
    "field_password": "Password:",
    "field_url": "URL:",
    "field_notes": "Notes:",
    "field_master_password": "Master Password:",
    "field_created": "Created:",
    "field_modified": "Modified:",
    
    "status_ready": "Ready",
    "status_entries": "entries",
    "status_showing": "Showing",
    "status_found": "Found",
    "status_of": "of",
    "status_no_matches": "No matches for",
    "status_all_match": "All",
    "status_entries_match": "entries match",
    "status_password_copied": "Password copied",
    "status_username_copied": "Username copied", 
    "status_url_copied": "URL copied",
    "status_totp_copied": "2FA code copied",
    "status_clipboard_cleared": "Clipboard cleared",
    "status_entry_added": "Entry added",
    "status_entry_updated": "Entry updated",
    "status_entry_deleted": "Entry deleted",
    "status_database_saved": "Database saved",
    "status_search_cleared": "Search cleared",
    "status_auto_backup": "Auto-backup created",
    "status_will_clear_in": "will clear in",
    "status_seconds": "s",
    "status_remaining": "s remaining",
    
    "error_title": "Error",
    "error_warning": "Warning", 
    "error_info": "Information",
    "error_success": "Success",
    "error_no_entry_selected": "Please select an entry!",
    "error_title_required": "Title is required!",
    "error_password_required": "Password is required!",
    "error_master_password_required": "Please enter master password!",
    "error_wrong_master_password": "Wrong master password or no database found!",
    "error_title_exists": "Entry with this title already exists!",
    "error_invalid_database_name": "Invalid database name!",
    "error_master_password_min_length": "Master password must be at least 8 characters!",
    "error_passwords_dont_match": "Passwords don't match!",
    "error_database_not_found": "Database not found!",
    "error_backup_not_found": "Backup file not found!",
    "error_could_not_open_website": "Could not open website:",
    "error_could_not_generate_totp": "Could not generate 2FA code!",
    "error_no_username_available": "No username available",
    "error_no_2fa_available": "No 2FA code available!",
    "error_backup_damaged": "The backup appears to be damaged (file too small).",
    
    "confirm_delete_entry": "Really delete",
    "confirm_cannot_be_undone": "This cannot be undone!",
    "confirm_logout": "Really logout?",
    "confirm_switch_database": "Switch database? Current session will be ended.",
    "confirm_exit_application": "Really exit application?",
    "confirm_overwrite_database": "Database already exists.\nOverwrite anyway?",
    "confirm_delete_database": "Really delete database",
    "confirm_import_backup": "Import data from",
    "confirm_check_preview": "Check the preview for correctness.",
    "confirm_restore_backup": "Restore current database with",
    
    "placeholder_search_entries": "Search entries...",
    "placeholder_database_name": "My_Passwords",
    
    "tooltip_add_entry": "Add new password entry (Ctrl+N)",
    "tooltip_edit_entry": "Edit selected entry (Ctrl+E)", 
    "tooltip_delete_entry": "Delete selected entry (Delete)",
    "tooltip_copy_password": "Copy password (Ctrl+C)",
    "tooltip_copy_username": "Copy username",
    "tooltip_password_generator": "Password generator",
    "tooltip_2fa_manager": "2FA/TOTP manager",
    "tooltip_backup_export": "Backup & export",
    "tooltip_settings": "Settings",
    "tooltip_database_switch": "Switch database (🔄)",
    "tooltip_logout": "Logout (🚪)",
    
    "info_enter_master_password": "Enter the master password for this database",
    "info_select_database": "Select a password database or create a new one",
    "info_double_click_open": "Double-click on a database to open directly",
    "info_tip_shortcuts": "Tip: F1/F5 work everywhere, others only in main window",
    "info_tip_double_click": "Tip: Double-click on a database to open directly",
    "info_tip_context_menu": "Tip: Right-click on entries for more options",
    "info_getting_started": "Welcome to Password Manager!\n\n• Use Ctrl+N to add new passwords\n• Use Ctrl+F to search entries\n• Right-click entries for more options\n• Use F1 to see all keyboard shortcuts\n\nYour passwords are encrypted and secure!",
    "info_auto_lock": "Database locked automatically for security.",
    "info_latest_version": "You are using the latest version of Password Manager!",
    "info_report_issue": "To report an issue:\n\n1. Describe the problem in detail\n2. Include steps to reproduce\n3. Mention your operating system\n\nContact: support@passwordmanager.com",
    "info_about": "🔐 Password Manager v2.0\n\nA secure password management application\nwith modern design and advanced features.\n\nFeatures:\n• AES-256 encryption\n• 2FA/TOTP support\n• Password generation\n• Secure backup & export\n• Auto-lock protection\n\nBuilt with Python & Tkinter",
    
    "settings_title": "Settings",
    "settings_saved": "Settings saved!",
    "settings_restart_required": "Some changes require restarting the application.\n\nPlease logout and login again to see all changes.",
    "settings_automatically_saved": "Settings are automatically saved",
    "settings_tab_security": "🔒 Security",
    "settings_tab_interface": "🎨 Interface", 
    "settings_tab_advanced": "⚙️ Advanced",
    "settings_auto_lock": "🔒 Auto Lock",
    "settings_auto_lock_enable": "Enable auto lock",
    "settings_timeout_minutes": "Timeout (minutes):",
    "settings_warning_seconds": "Warning (seconds):",
    "settings_clipboard": "📋 Clipboard",
    "settings_clipboard_enable": "Enable automatic clearing",
    "settings_clear_after_seconds": "Clear after (seconds):",
    "settings_design": "🎨 Design",
    "settings_theme": "Theme:",
    "settings_theme_windows_classic": "Windows Classic",
    "settings_theme_modern": "Modern (Future)",
    "settings_theme_dark": "Dark Mode (Future)",
    "settings_window": "🖥️ Window",
    "settings_show_status_bar": "Show status bar",
    "settings_show_toolbar_icons": "Show toolbar icons",
    "settings_remember_window_size": "Remember window size",
    "settings_startup": "🚀 Program Start",
    "settings_remember_database": "Remember last database",
    "settings_start_minimized": "Start minimized",
    "settings_import_export": "💾 Settings",
    "settings_export": "📤 Export",
    "settings_import": "📥 Import", 
    "settings_reset": "🔄 Reset",
    "settings_language": "🌍 Language",
    "settings_select_language": "Select Language:",
    
    "backup_title": "Backup & Export",
    "backup_tab_backup": "💾 Backup",
    "backup_tab_export": "📤 Export",
    "backup_tab_import": "📥 Import",
    "backup_quick_actions": "⚡ Quick Actions",
    "backup_create": "🔄 Create Backup",
    "backup_full": "📦 Full Backup",
    "backup_available": "📋 Available Backups",
    "backup_restore": "↩️ Restore",
    "backup_delete": "🗑️ Delete",
    "backup_export_settings": "⚙️ Export Settings",
    "backup_include_passwords": "🔑 Include passwords in export",
    "backup_warning": "⚠️ Warning: Exported files are NOT encrypted!",
    "backup_export_formats": "📁 Export Formats",
    "backup_export_csv": "📊 Export CSV",
    "backup_export_json": "📋 Export JSON",
    "backup_format_info": "ℹ️ Format Information",
    "backup_import_settings": "⚙️ Import Settings",
    "backup_overwrite_existing": "🔄 Overwrite existing entries",
    "backup_import_sources": "📁 Import Sources",
    "backup_import_csv": "📊 Import CSV",
    "backup_restore_backup": "💾 Restore Backup",
    "backup_import_preview": "👁️ Import Preview",
    "backup_statistics": "backups",
    
    "generator_title": "🎲 Password Generator",
    "generator_settings": "⚙️ Settings",
    "generator_length": "Length:",
    "generator_uppercase": "✓ Uppercase (A-Z)",
    "generator_lowercase": "✓ Lowercase (a-z)",
    "generator_numbers": "✓ Numbers (0-9)",
    "generator_symbols": "✓ Symbols (!@#$%...)",
    "generator_exclude_ambiguous": "✓ Exclude ambiguous characters (0,O,l,1...)",
    "generator_generated_password": "🔑 Generated Password",
    "generator_strength": "Strength:",
    "generator_actions": "🎯 Actions",
    "generator_generate_new": "🎲 New Password",
    "generator_use_password": "✅ Use",
    "generator_history": "📜 Recent Passwords",
    "generator_tip": "Tip: Double-click on a password from history to select",
    
    "totp_title": "🔐 2FA/TOTP Manager",
    "totp_subtitle": "Manage all your 2FA codes in one place",
    "totp_active_codes": "🔑 Active 2FA Codes",
    "totp_account": "📝 Account",
    "totp_current_code": "🔐 Current Code",
    "totp_time": "⏱️ Time",
    "totp_copy_code": "📋 Copy Code",
    "totp_show_qr": "📱 Show QR Code",
    "totp_backup_codes": "💾 Backup Codes",
    "totp_refresh": "🔄 Refresh",
    "totp_tip": "💡 Tip: Click on an entry to select it, then 'Copy Code'. Codes update automatically every 30 seconds.",
    "totp_no_codes": "No 2FA codes available",
    "totp_add_2fa": "Add 2FA to your passwords",
    "totp_qr_title": "📱 QR Code for",
    "totp_secret_backup": "Secret Key (Backup):",
    "totp_copy_secret": "📋 Copy Secret",
    "totp_backup_title": "💾 Backup Recovery Codes",
    "totp_backup_warning": "⚠️ These codes can be used when you don't have access\nto your 2FA app. Keep them safe!",
    "totp_copy_all": "📋 Copy All",
    "totp_save": "💾 Save",
    "totp_backup_header": "BACKUP RECOVERY CODES",
    "totp_generated": "Generated:",
    "totp_keep_safe": "Keep these codes safe!",
    "totp_codes_copied": "All backup codes copied to clipboard!",
    "totp_codes_saved": "Backup codes saved:",
    "totp_could_not_save": "Could not save file:",
    "totp_code_copied": "2FA code copied!",
    "totp_valid_for": "Valid for",
    "totp_secret_copied": "Secret key copied to clipboard!",
    
    "password_strength_very_weak": "Very Weak",
    "password_strength_weak": "Weak",
    "password_strength_medium": "Medium",
    "password_strength_strong": "Strong", 
    "password_strength_very_strong": "Very Strong",
    
    "database_manager_title": "🗄️ Database Manager",
    "database_manager_subtitle": "Select a password database or create a new one",
    "database_available": "📂 Available Databases",
    "database_name": "📝 Database Name",
    "database_size": "📏 Size",
    "database_modified": "🕐 Last Modified",
    "database_none_found": "No databases found",
    "database_create_new": "Create a new database!",
    "database_found": "database",
    "database_found_plural": "databases found",
    
    "context_edit_entry": "✏️ Edit Entry",
    "context_copy_password": "📋 Copy Password",
    "context_copy_username": "👤 Copy Username",
    "context_copy_2fa": "🔐 Copy 2FA Code",
    "context_copy_url": "🔗 Copy URL",
    "context_open_website": "🌐 Open",
    "context_no_url": "🌐 Open Website (no URL)",
    "context_search_similar": "🔍 Search Similar",
    "context_duplicate_entry": "📝 Duplicate Entry",
    "context_delete_entry": "🗑️ Delete Entry",
    "context_entry_details": "ℹ️ Entry Details",
    "context_password_strength": "📊 Password Strength",
    
    "details_title": "ℹ️",
    "details_for": "Details for",
    "details_info": "Entry Information",
    "details_title_field": "📝 Title:",
    "details_username_field": "👤 Username:", 
    "details_password_field": "🔑 Password:",
    "details_url_field": "🌐 URL:",
    "details_2fa_field": "🔐 2FA:",
    "details_created_field": "📅 Created:",
    "details_modified_field": "✏️ Modified:",
    "details_notes_field": "📋 Notes",
    "details_not_specified": "(not specified)",
    "details_empty": "(empty)",
    "details_enabled": "Enabled",
    "details_disabled": "Disabled",
    "details_unknown": "Unknown",
    "details_copy_password": "📋 Password",
    "details_copy_user": "👤 User",
    "details_open_url": "🌐 Open",
    
    "strength_dialog_title": "Password Strength",
    "strength_dialog_for": "Password strength for",
    "strength_dialog_strength": "Strength:",
    "strength_dialog_score": "Score:",
    "strength_dialog_length": "Length:",
    "strength_dialog_characters": "characters",
    
    "weak_passwords_title": "Weak Passwords",
    "weak_passwords_found": "Weak passwords found:",
    "weak_passwords_and_more": "... and",
    "weak_passwords_more": "more",
    "weak_passwords_none": "All passwords are strong!",
    
    "duplicate_passwords_title": "Duplicate Passwords", 
    "duplicate_passwords_found": "Duplicate passwords found:",
    "duplicate_passwords_used_by": "Password used by:",
    "duplicate_passwords_groups": "more groups",
    "duplicate_passwords_none": "No duplicate passwords found!",
    
    "duplicate_entry_title": "Duplicate Entry",
    "duplicate_entry_copy": "(Copy)",
    "duplicate_entry_success": "Entry duplicated:",
    "duplicate_entry_error": "Could not duplicate entry. Title already exists?",
    
    "auto_lock_warning_title": "⚠️ Auto-Lock Warning",
    "auto_lock_warning_title_short": "Auto Lock",
    "auto_lock_warning_text": "The database will be automatically locked for security reasons\nas no activity was detected.\n\n💡 Tip: In open dialogs the timer is automatically paused.",
    "auto_lock_warning_locking_in": "Locking in",
    "auto_lock_warning_seconds": "seconds",
    "auto_lock_warning_continue": "✅ Continue Working",
    "auto_lock_warning_lock_now": "🔒 Lock Now",
    
    "search_advanced_title": "🔍 Advanced Search",
    "search_term": "Search term:",
    "search_results": "Search Results:",
    "search_in": "Search in:",
    "search_in_title": "Title",
    "search_in_username": "Username",
    "search_in_url": "URL", 
    "search_in_notes": "Notes",
    
    "csv_preview": "📊 CSV Preview:",
    "csv_fields": "Fields:",
    "csv_row": "Row",
    "csv_no_data": "❌ No valid data found",
    "csv_more_rows": "... (more rows available)",
    "csv_error_reading": "❌ Error reading CSV file:",
    
    "import_csv_title": "CSV Import",
    "import_csv_from": "Import data from",
    "import_csv_success": "CSV Import:",
    "import_csv_imported": "entries imported",
    "import_csv_conflicts": "conflicts",
    "import_csv_error": "CSV import error:",
    
    "export_csv_title": "Save CSV Export",
    "export_json_title": "Save JSON Export", 
    "export_csv_success": "CSV export created:",
    "export_json_success": "JSON export created:",
    "export_csv_error": "CSV export error:",
    "export_json_error": "JSON export error:",
    
    "backup_create_title": "Save Full Backup",
    "backup_created": "Full backup created:",
    "backup_restored": "Backup restored:",
    "backup_deleted": "Backup deleted",
    "backup_error": "Backup error:",
    "backup_restore_error": "Restore error:",
    "backup_delete_error": "Delete error:",
    "backup_import_title": "Select Backup File",
    "backup_import_name": "Name for imported database:",
    "backup_import_success": "Backup successfully imported as",
    "backup_import_error": "Backup could not be imported:",
    "backup_import_open_now": "Would you like to open the imported database now?",
    
    "login_title": "🔐",
    "login_database": "Database:",
    "login_back": "⬅️ Back",
    "login_login": "🔓 Login",
    
    "new_database_title": "New Database",
    "new_database_name": "Name for the new database:",
    "new_database_master_password": "Master password for",
    "new_database_confirm": "Repeat master password:",
    "new_database_created": "Database successfully created!",
    "new_database_error": "Database could not be created:",
    
    "file_types_backup": "Backup Files",
    "file_types_encrypted": "Encrypted Files", 
    "file_types_csv": "CSV Files",
    "file_types_json": "JSON Files",
    "file_types_text": "Text Files",
    "file_types_zip": "ZIP Archives",
    "file_types_all": "All Files"
}